import assert from 'node:assert/strict';
import {test,after} from 'node:test';
import {build} from 'esbuild';
import {writeFile,rm} from 'node:fs/promises';
const path=new URL('../.bow-collision-test.mjs',import.meta.url);
const bundled=await build({stdin:{contents:`export {BowGameRuntime} from './src/BowGameRuntime.ts';export {BowCollision,PLAYER_HEIGHT} from './src/BowCollision.ts';export {buildBowArena} from './src/BowArena.ts';export * from 'three';`,resolveDir:new URL('..',import.meta.url).pathname,loader:'ts'},bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'three-only',setup(b){b.onResolve({filter:/^threepipe$/},()=>({path:new URL('../node_modules/three/build/three.module.js',import.meta.url).pathname}));}}]});
await writeFile(path,bundled.outputFiles[0].text);after(()=>rm(path,{force:true}));
globalThis.ImageData??=class {};
const {BowGameRuntime,BowCollision,buildBowArena,Vector3,Group,Mesh,MeshBasicMaterial,BoxGeometry,PlaneGeometry,SphereGeometry,Raycaster,DoubleSide,InstancedMesh,Matrix4}=await import(path.href);
// Canvas painting only is inert; every seeded random call and all real arena triangles remain unchanged.
const context=new Proxy({createRadialGradient(){return {addColorStop(){}};}},{get:(o,k)=>o[k]??(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
globalThis.document={createElement(){return {getContext(){return context;}};}};
const arena=buildBowArena(),world=new BowCollision(arena.group);
after(()=>{world.dispose();delete globalThis.document;});
const dt=1/120;
function advance(c,p,v,n,dx=0,dz=0){let ground=false;for(let i=0;i<n;i++){v.x=dx;v.z=dz;v.y-=9.81*dt;ground=c.move(p,v,dt);}return ground;}
function fixture(){const g=new Group();const material=new MeshBasicMaterial({side:DoubleSide});const floor=new Mesh(new PlaneGeometry(40,40),material);floor.rotation.x=-Math.PI/2;floor.userData.bowSolid=true;g.add(floor);const crate=new Mesh(new BoxGeometry(1,.95,1),material);crate.position.set(0,.475,0);crate.userData.bowSolid=true;g.add(crate);return new BowCollision(g);}
test('arrows meet actual weathered granite triangles within 1 cm of reference raycast',()=>{
 arena.group.traverse(m=>{if(m.isMesh)m.material.side=DoubleSide;});
 const rocks=arena.group.children.filter(m=>m.name==='Weathered granite');
 for(const rock of rocks){rock.material.side=DoubleSide;const a=rock.position.clone().add(new Vector3(.031,.137,rock.scale.z*2)),b=rock.position.clone().add(new Vector3(.031,.137,0));const ref=new Raycaster(a,b.clone().sub(a).normalize()).intersectObjects(arena.group.children.filter(m=>m.userData.bowSolid))[0];assert.ok(ref);const hit=world.segment(a,b);assert.ok(hit);assert.ok(hit.point.distanceTo(ref.point)<.01,JSON.stringify({rock:rock.position.toArray(),hit:hit.point.toArray(),ref:ref.point.toArray(),object:ref.object.name}));}
});
test('capsule rests on visible floor at -0.04, and remains supported',()=>{const p=new Vector3(0,3,17),v=new Vector3();assert.ok(advance(world,p,v,240));assert.ok(Math.abs(p.y+.04)<.001);assert.ok(world.penetration(p)<.001);});
test('walking and sprinting into a rock stop with under 1 cm penetration',()=>{for(const speed of [4.5,7]){const p=new Vector3(9,0,10),v=new Vector3();advance(world,p,v,360,0,-speed);assert.ok(p.z>6.5,p.toArray().join(','));assert.ok(world.penetration(p)<.01);}});
test('unchanged jump lands on crate top, then walking off falls to floor',()=>{const c=fixture(),p=new Vector3(0,0,1.35),v=new Vector3();advance(c,p,v,2);v.y=4.8;advance(c,p,v,38,0,-4.5);assert.ok(advance(c,p,v,160));assert.ok(Math.abs(p.y-.95)<.002,p.toArray().join(','));advance(c,p,v,120,4.5,0);advance(c,p,v,120);assert.ok(Math.abs(p.y)<.002);c.dispose();});
test('all solo and ten online slot spawns are free, including embedded spawn recovery',()=>{const wanted=[arena.playerSpawn,...arena.botSpawns];for(let slot=1;slot<10;slot++){const b=arena.botSpawns[(slot-1)%3],r=Math.floor((slot-1)/3);wanted.push(new Vector3(b.x+(r%2?5:-5)*r,b.y,b.z+(r%2?-4:4)*r));}wanted.push(new Vector3(9,1,5),new Vector3(6.7,.4,-3.7));for(const w of wanted){const p=world.spawn(w,.42);assert.ok(world.penetration(p,.42)<.001);const v=new Vector3();assert.ok(advance(world,p,v,2));} });
test('solid instancing expands world transforms; untagged decoration stays passable',()=>{const group=new Group();group.position.x=3;const m=new InstancedMesh(new BoxGeometry(1,1,1),new MeshBasicMaterial(),2);m.userData.bowSolid=true;m.setMatrixAt(0,new Matrix4().makeTranslation(0,1,0));m.setMatrixAt(1,new Matrix4().makeTranslation(3,1,0));group.add(m);const decoration=new Mesh(new SphereGeometry(1),m.material);decoration.position.set(9,1,0);group.add(decoration);const c=new BowCollision(group);assert.equal(c.solidMeshes,2);for(const x of [3,6])assert.ok(c.segment(new Vector3(x,1,2),new Vector3(x,1,-2)));assert.equal(c.segment(new Vector3(12,1,2),new Vector3(12,1,-2)),null);c.dispose();});
test('full arena collision cost benchmark (four capsules per fixed step)',()=>{const p=[new Vector3(9,0,8),new Vector3(-8,0,11),new Vector3(0,0,17),new Vector3(6.7,2,-3.7)],v=p.map(()=>new Vector3());const timings=[];for(let i=0;i<1200;i++){const start=performance.now();p.forEach((q,j)=>advance(world,q,v[j],1,0,j<2?-4.5:0));timings.push(performance.now()-start);}timings.sort((a,b)=>a-b);console.log(JSON.stringify({bvh:world.stats(),fourCapsuleStepMs:{p50:timings[600],p95:timings[1140],max:timings.at(-1)}}));assert.ok(world.buildMs<300);});

test('world and player hits compete by nearest distance; remote visuals never apply damage',()=>{
 const setup=()=>{const game=new BowGameRuntime({});game.config={scoreLimit:10,obstacles:[]};game.collision=world;game.player.set(0,0,17);const target={mesh:new Group(),hp:100,kills:0,deaths:0,name:'test'};game.bots=[target];return {game,target};};
 const run=game=>{for(let i=0;i<20;i++)game.stepArrows(dt);};
 const blocked=setup();blocked.target.mesh.position.set(9,0,4);blocked.game.fire(new Vector3(9,1.05,10),new Vector3(0,0,-1),-1,1);run(blocked.game);assert.equal(blocked.target.hp,100);assert.ok(blocked.game.lastWorldImpact);assert.ok(blocked.game.arrows[0].stuck);
 const near=setup();near.target.mesh.position.set(9,0,9);near.game.fire(new Vector3(9,1.05,10),new Vector3(0,0,-1),-1,1);run(near.game);assert.equal(near.target.hp,30);assert.equal(near.game.lastWorldImpact,null);
 const remote=setup();remote.game.player.set(9,0,9);remote.game.spawnArrow(new Vector3(9,1.05,10),new Vector3(0,0,-56),0,'remote',true);run(remote.game);assert.equal(remote.game.hp,100);assert.ok(remote.game.arrows[0].stuck);assert.equal(remote.game.arrows[0].mesh.visible,false);assert.equal(remote.game.lastWorldImpact,null);
});
test('all required arena parts are solid; foliage, grass and scree are excluded',()=>{const names=new Set();arena.group.traverse(m=>{if(m.isMesh&&m.userData.bowSolid)names.add(m.name);});assert.deepEqual([...names].sort(),['Forest floor','Weathered granite','Pine trunk','Ruined stone wall','Broken wall cap','Supply crate','Crate strap','Shelter post','Weathered shelter tarp','Salvaged barricade plank','Fallen pine'].sort());assert.equal(world.solidMeshes,129);});
test('real runtime jump input lands on the authored crate without a second jump',()=>{const game=new BowGameRuntime({});game.config={obstacles:[],scoreLimit:10};game.collision=world;game.player.set(6.7,0,-2.35);for(let i=0;i<30;i++)game.step(dt);game.keys.add('Space');game.keys.add('KeyW');game.step(dt);game.keys.delete('Space');for(let i=0;i<51;i++)game.step(dt);game.keys.clear();for(let i=0;i<160;i++)game.step(dt);assert.ok(game.grounded);assert.ok(game.player.y>.9&&game.player.y<1);});

test('spawn stays under the open shelter canopy instead of treating the tarp as a filled volume',()=>{const p=world.spawn(new Vector3(11.5,0,-18));assert.ok(p.distanceTo(new Vector3(11.5,-.04,-18))<.001);});
test('walkable slope supports the capsule; a steep face does not report ground',()=>{for(const angle of [45,60]){const group=new Group(),ramp=new Mesh(new PlaneGeometry(20,20),new MeshBasicMaterial({side:DoubleSide}));ramp.rotation.set(-Math.PI/2,angle*Math.PI/180,0);ramp.userData.bowSolid=true;group.add(ramp);const c=new BowCollision(group),p=new Vector3(0,.2,0),v=new Vector3();const grounded=advance(c,p,v,60);assert.equal(grounded,angle===45);assert.ok(c.penetration(p)<.01);c.dispose();}});
console.log('legacy collision inventory',JSON.stringify({covers:arena.obstacles.length,trunkCylinders:arena.group.children.filter(m=>m.name==='Pine trunk'&&arena.obstacles.some(o=>o.x===m.position.x&&o.z===m.position.z)).length}));

test('spawn clearance rejects a thin canopy piercing the capsule axis',()=>{const group=new Group(),roof=new Mesh(new PlaneGeometry(4,4),new MeshBasicMaterial({side:DoubleSide}));roof.rotation.x=-Math.PI/2;roof.position.y=1;roof.userData.bowSolid=true;group.add(roof);const c=new BowCollision(group);assert.ok(c.penetration(new Vector3(0,0,0))>.3);const spawn=c.spawn(new Vector3(0,0,0));assert.ok(spawn.y>=1);assert.ok(c.penetration(spawn)<.001);c.dispose();});
